### ISSUE TITLE
Add a length limit to messages

### ISSUE THREAD

**Issue by noftaly** [Romitou/SwanDashboard#77]
Messages (automatic-messages, error details, etc.) should not have a length greater than 2000 (including markdown.)
It would be great to disable the "submit" button with maybe a tooltip explaining that the message is too long (client-side would be the best imo.)

**Comment by WeeskyBDW** [comment]
It's better to check on client and server side imo. Why ? Because a maliscious user can change javascript who block and send a too bigest message. It will not crash all the panel but made errors in Doctrine (and in sentry).

"Never trust user"

**Comment by noftaly** [comment]
Yeah whatever. I meant that we shouldn't be able to click the button if the message is not valid, rather than sending the message and then getting a flash error

**Comment by WeeskyBDW** [comment]
PHP will send an error only if user disable Javascript limitation

**Comment by noftaly** [comment]
I wasn't talking about a php error. Of course it won't error out on its own if the message's length is greater than 2000. I was talking about server-side verification. So yes, it should have both, but i was reminding whoever will implement this, that it would be better if there is also a client side verification for a better UX

**Comment by WeeskyBDW** [comment]
Yes that what i say in beginning of my first comment xD
